#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MySites_LN")]
public partial class PagesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertSiteContent(SiteContent instance);
  partial void UpdateSiteContent(SiteContent instance);
  partial void DeleteSiteContent(SiteContent instance);
  #endregion
	
	public PagesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LNSS"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PagesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PagesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PagesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PagesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<SiteContent> SiteContents
	{
		get
		{
			return this.GetTable<SiteContent>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SiteContent")]
public partial class SiteContent : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _MainContent;
	
	private string _Hkey;
	
	private string _Hdescription;
	
	private string _PageId;
	
	private string _PageTitle;
	
	private string _OriginalUrl;
	
	private string _MappedUrl;
	
	private string _Caption;
	
	private int _SubCat;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMainContentChanging(string value);
    partial void OnMainContentChanged();
    partial void OnHkeyChanging(string value);
    partial void OnHkeyChanged();
    partial void OnHdescriptionChanging(string value);
    partial void OnHdescriptionChanged();
    partial void OnPageIdChanging(string value);
    partial void OnPageIdChanged();
    partial void OnPageTitleChanging(string value);
    partial void OnPageTitleChanged();
    partial void OnOriginalUrlChanging(string value);
    partial void OnOriginalUrlChanged();
    partial void OnMappedUrlChanging(string value);
    partial void OnMappedUrlChanged();
    partial void OnCaptionChanging(string value);
    partial void OnCaptionChanged();
    partial void OnSubCatChanging(int value);
    partial void OnSubCatChanged();
    #endregion
	
	public SiteContent()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainContent", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string MainContent
	{
		get
		{
			return this._MainContent;
		}
		set
		{
			if ((this._MainContent != value))
			{
				this.OnMainContentChanging(value);
				this.SendPropertyChanging();
				this._MainContent = value;
				this.SendPropertyChanged("MainContent");
				this.OnMainContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hkey", DbType="NVarChar(250)")]
	public string Hkey
	{
		get
		{
			return this._Hkey;
		}
		set
		{
			if ((this._Hkey != value))
			{
				this.OnHkeyChanging(value);
				this.SendPropertyChanging();
				this._Hkey = value;
				this.SendPropertyChanged("Hkey");
				this.OnHkeyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hdescription", DbType="NVarChar(500)")]
	public string Hdescription
	{
		get
		{
			return this._Hdescription;
		}
		set
		{
			if ((this._Hdescription != value))
			{
				this.OnHdescriptionChanging(value);
				this.SendPropertyChanging();
				this._Hdescription = value;
				this.SendPropertyChanged("Hdescription");
				this.OnHdescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageId", DbType="NVarChar(50)")]
	public string PageId
	{
		get
		{
			return this._PageId;
		}
		set
		{
			if ((this._PageId != value))
			{
				this.OnPageIdChanging(value);
				this.SendPropertyChanging();
				this._PageId = value;
				this.SendPropertyChanged("PageId");
				this.OnPageIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PageTitle", DbType="NVarChar(500)")]
	public string PageTitle
	{
		get
		{
			return this._PageTitle;
		}
		set
		{
			if ((this._PageTitle != value))
			{
				this.OnPageTitleChanging(value);
				this.SendPropertyChanging();
				this._PageTitle = value;
				this.SendPropertyChanged("PageTitle");
				this.OnPageTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalUrl", DbType="NVarChar(50)")]
	public string OriginalUrl
	{
		get
		{
			return this._OriginalUrl;
		}
		set
		{
			if ((this._OriginalUrl != value))
			{
				this.OnOriginalUrlChanging(value);
				this.SendPropertyChanging();
				this._OriginalUrl = value;
				this.SendPropertyChanged("OriginalUrl");
				this.OnOriginalUrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MappedUrl", DbType="NVarChar(50)")]
	public string MappedUrl
	{
		get
		{
			return this._MappedUrl;
		}
		set
		{
			if ((this._MappedUrl != value))
			{
				this.OnMappedUrlChanging(value);
				this.SendPropertyChanging();
				this._MappedUrl = value;
				this.SendPropertyChanged("MappedUrl");
				this.OnMappedUrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(50)")]
	public string Caption
	{
		get
		{
			return this._Caption;
		}
		set
		{
			if ((this._Caption != value))
			{
				this.OnCaptionChanging(value);
				this.SendPropertyChanging();
				this._Caption = value;
				this.SendPropertyChanged("Caption");
				this.OnCaptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubCat", DbType="Int NOT NULL")]
	public int SubCat
	{
		get
		{
			return this._SubCat;
		}
		set
		{
			if ((this._SubCat != value))
			{
				this.OnSubCatChanging(value);
				this.SendPropertyChanging();
				this._SubCat = value;
				this.SendPropertyChanged("SubCat");
				this.OnSubCatChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
